import { defineConfig } from "tsup";

export default defineConfig({
  entry: [
    "src/main.ts",
    "src/run.ts",
    "src/attempts.ts",
    "src/cancel.ts",
    "src/diseaseRiskCadence.ts",
    "src/diseaseRiskReport.ts",
    "src/diseaseRiskSchedule.ts",
    "src/drain.ts",
    "src/enqueue.ts",
    "src/fieldReportReadModel.ts",
    "src/hailRefreshCadence.ts",
    "src/hailRefreshReport.ts",
    "src/health.ts",
    "src/hailRefreshSchedule.ts",
    "src/imageryCadence.ts",
    "src/imageryProbeSchedule.ts",
    "src/imageryProbeReport.ts",
    "src/imagerySyncReport.ts",
    "src/imagerySyncSchedule.ts",
    "src/imageryProviderProbeHistory.ts",
    "src/smoke.ts",
    "src/inspect.ts",
    "src/metrics.ts",
    "src/marketRefreshQuotes.ts",
    "src/marketRefreshReport.ts",
    "src/marketCadence.ts",
    "src/marketRefreshSchedule.ts",
    "src/marketUpsertPrice.ts",
    "src/marketUpsertBasis.ts",
    "src/marketUpsertYield.ts",
    "src/moistureCellBackfillSchedule.ts",
    "src/phaseSummary.ts",
    "src/phases.ts",
    "src/recoverStale.ts",
    "src/replay.ts",
    "src/summary.ts",
    "src/replayFailed.ts",
    "src/watch.ts",
    "src/zoneActivityReport.ts",
    "src/weatherRefreshReport.ts",
    "src/weatherRefreshSchedule.ts",
  ],
  format: ["esm"],
  target: "node24",
  outDir: "dist",
  clean: true,
  platform: "node",
  noExternal: [/^@fieldpulse\//],
});
