// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/auth/check-email" | "/auth/sign-in" | "/fields/[fieldId]" | "/preview" | "/share/[token]"
type AppRouteHandlerRoutes = "/api/auth/actor" | "/api/auth/email" | "/api/auth/signout" | "/api/field-intake/geofile/create" | "/api/field-intake/geofile/parse" | "/api/field-intake/lld/create" | "/api/field-intake/lld/lookup" | "/api/field-intake/spreadsheet/batches" | "/api/field-intake/spreadsheet/batches/[batchId]/commit" | "/api/field-intake/spreadsheet/preview" | "/api/fields" | "/api/fields/[fieldId]/basis-assumption" | "/api/fields/[fieldId]/crop-report-export" | "/api/fields/[fieldId]/notes" | "/api/fields/[fieldId]/overview" | "/api/fields/[fieldId]/report-export" | "/api/fields/[fieldId]/yield-assumption" | "/api/imagery/providers" | "/api/imagery/providers/probes" | "/api/jobs/dispatches" | "/api/market/prices" | "/api/settings" | "/auth/callback"
type PageRoutes = never
type LayoutRoutes = "/"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/api/auth/actor": {}
  "/api/auth/email": {}
  "/api/auth/signout": {}
  "/api/field-intake/geofile/create": {}
  "/api/field-intake/geofile/parse": {}
  "/api/field-intake/lld/create": {}
  "/api/field-intake/lld/lookup": {}
  "/api/field-intake/spreadsheet/batches": {}
  "/api/field-intake/spreadsheet/batches/[batchId]/commit": { "batchId": string; }
  "/api/field-intake/spreadsheet/preview": {}
  "/api/fields": {}
  "/api/fields/[fieldId]/basis-assumption": { "fieldId": string; }
  "/api/fields/[fieldId]/crop-report-export": { "fieldId": string; }
  "/api/fields/[fieldId]/notes": { "fieldId": string; }
  "/api/fields/[fieldId]/overview": { "fieldId": string; }
  "/api/fields/[fieldId]/report-export": { "fieldId": string; }
  "/api/fields/[fieldId]/yield-assumption": { "fieldId": string; }
  "/api/imagery/providers": {}
  "/api/imagery/providers/probes": {}
  "/api/jobs/dispatches": {}
  "/api/market/prices": {}
  "/api/settings": {}
  "/auth/callback": {}
  "/auth/check-email": {}
  "/auth/sign-in": {}
  "/fields/[fieldId]": { "fieldId": string; }
  "/preview": {}
  "/share/[token]": { "token": string; }
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
