// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../src/app/auth/check-email/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/auth/check-email">> = Specific
  const handler = {} as typeof import("../../src/app/auth/check-email/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/auth/sign-in/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/auth/sign-in">> = Specific
  const handler = {} as typeof import("../../src/app/auth/sign-in/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/fields/[fieldId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/fields/[fieldId]">> = Specific
  const handler = {} as typeof import("../../src/app/fields/[fieldId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/preview/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/preview">> = Specific
  const handler = {} as typeof import("../../src/app/preview/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/actor/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/actor">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/actor/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/email/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/email">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/email/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/signout/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/signout">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/signout/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/field-intake/geofile/create/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/field-intake/geofile/create">> = Specific
  const handler = {} as typeof import("../../src/app/api/field-intake/geofile/create/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/field-intake/geofile/parse/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/field-intake/geofile/parse">> = Specific
  const handler = {} as typeof import("../../src/app/api/field-intake/geofile/parse/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/field-intake/lld/create/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/field-intake/lld/create">> = Specific
  const handler = {} as typeof import("../../src/app/api/field-intake/lld/create/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/field-intake/lld/lookup/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/field-intake/lld/lookup">> = Specific
  const handler = {} as typeof import("../../src/app/api/field-intake/lld/lookup/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/field-intake/spreadsheet/batches/[batchId]/commit/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/field-intake/spreadsheet/batches/[batchId]/commit">> = Specific
  const handler = {} as typeof import("../../src/app/api/field-intake/spreadsheet/batches/[batchId]/commit/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/field-intake/spreadsheet/batches/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/field-intake/spreadsheet/batches">> = Specific
  const handler = {} as typeof import("../../src/app/api/field-intake/spreadsheet/batches/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/field-intake/spreadsheet/preview/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/field-intake/spreadsheet/preview">> = Specific
  const handler = {} as typeof import("../../src/app/api/field-intake/spreadsheet/preview/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/fields/[fieldId]/basis-assumption/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/fields/[fieldId]/basis-assumption">> = Specific
  const handler = {} as typeof import("../../src/app/api/fields/[fieldId]/basis-assumption/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/fields/[fieldId]/crop-report-export/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/fields/[fieldId]/crop-report-export">> = Specific
  const handler = {} as typeof import("../../src/app/api/fields/[fieldId]/crop-report-export/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/fields/[fieldId]/notes/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/fields/[fieldId]/notes">> = Specific
  const handler = {} as typeof import("../../src/app/api/fields/[fieldId]/notes/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/fields/[fieldId]/overview/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/fields/[fieldId]/overview">> = Specific
  const handler = {} as typeof import("../../src/app/api/fields/[fieldId]/overview/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/fields/[fieldId]/report-export/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/fields/[fieldId]/report-export">> = Specific
  const handler = {} as typeof import("../../src/app/api/fields/[fieldId]/report-export/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/fields/[fieldId]/yield-assumption/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/fields/[fieldId]/yield-assumption">> = Specific
  const handler = {} as typeof import("../../src/app/api/fields/[fieldId]/yield-assumption/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/fields/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/fields">> = Specific
  const handler = {} as typeof import("../../src/app/api/fields/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/imagery/providers/probes/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/imagery/providers/probes">> = Specific
  const handler = {} as typeof import("../../src/app/api/imagery/providers/probes/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/imagery/providers/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/imagery/providers">> = Specific
  const handler = {} as typeof import("../../src/app/api/imagery/providers/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/jobs/dispatches/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/jobs/dispatches">> = Specific
  const handler = {} as typeof import("../../src/app/api/jobs/dispatches/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/market/prices/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/market/prices">> = Specific
  const handler = {} as typeof import("../../src/app/api/market/prices/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/settings/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/settings">> = Specific
  const handler = {} as typeof import("../../src/app/api/settings/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/auth/callback/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/auth/callback">> = Specific
  const handler = {} as typeof import("../../src/app/auth/callback/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
