create table if not exists app.rate_limit_events (
  id bigint generated by default as identity primary key,
  scope text not null,
  identifier text not null,
  created_at timestamptz not null default timezone('utc', now()),
  constraint rate_limit_events_scope_present check (length(btrim(scope)) > 0),
  constraint rate_limit_events_identifier_present check (
    length(btrim(identifier)) > 0
  )
);

create index if not exists rate_limit_events_scope_identifier_created_idx
  on app.rate_limit_events (scope, identifier, created_at desc);

create or replace function app.consume_rate_limit(
  target_scope text,
  target_identifier text,
  max_attempts integer,
  window_seconds integer
)
returns table (
  allowed boolean,
  limit_count integer,
  remaining_count integer,
  retry_after_seconds integer,
  reset_at timestamptz
)
language plpgsql
security invoker
set search_path = app, public, extensions
as $$
declare
  now_utc timestamptz := timezone('utc', now());
  window_start timestamptz;
  window_end timestamptz;
  recent_attempt_count integer;
  oldest_recent_attempt timestamptz;
begin
  if max_attempts < 1 then
    raise exception 'max_attempts must be at least 1';
  end if;

  if window_seconds < 1 then
    raise exception 'window_seconds must be at least 1';
  end if;

  if target_scope is null or length(btrim(target_scope)) = 0 then
    raise exception 'target_scope is required';
  end if;

  if target_identifier is null or length(btrim(target_identifier)) = 0 then
    raise exception 'target_identifier is required';
  end if;

  window_start := now_utc - make_interval(secs => window_seconds);
  window_end := now_utc + make_interval(secs => window_seconds);

  perform pg_advisory_xact_lock(
    hashtextextended(target_scope || ':' || target_identifier, 0)
  );

  delete from app.rate_limit_events
  where scope = target_scope
    and identifier = target_identifier
    and created_at < now_utc - make_interval(secs => greatest(window_seconds * 4, 86400));

  select
    count(*)::integer,
    min(created_at)
  into recent_attempt_count, oldest_recent_attempt
  from app.rate_limit_events
  where scope = target_scope
    and identifier = target_identifier
    and created_at >= window_start;

  if recent_attempt_count >= max_attempts then
    allowed := false;
    limit_count := max_attempts;
    remaining_count := 0;
    reset_at := coalesce(
      oldest_recent_attempt + make_interval(secs => window_seconds),
      window_end
    );
    retry_after_seconds := greatest(
      1,
      ceil(extract(epoch from (reset_at - now_utc)))::integer
    );
    return next;
    return;
  end if;

  insert into app.rate_limit_events (scope, identifier)
  values (target_scope, target_identifier);

  recent_attempt_count := recent_attempt_count + 1;

  allowed := true;
  limit_count := max_attempts;
  remaining_count := greatest(max_attempts - recent_attempt_count, 0);
  reset_at := coalesce(
    oldest_recent_attempt + make_interval(secs => window_seconds),
    window_end
  );
  retry_after_seconds := greatest(
    0,
    ceil(extract(epoch from (reset_at - now_utc)))::integer
  );
  return next;
end;
$$;

grant execute on function app.consume_rate_limit(text, text, integer, integer) to service_role;
